# Generated by Django 3.0.3 on 2021-10-18 19:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import home.logic


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211012_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'get_latest_by': '-date_create', 'ordering': ['-date_create'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Customer', verbose_name='Логин'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания заказа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оформления заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=home.logic.get_timestamp_path, verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество товара')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='Общая цена')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Order', verbose_name='Заказ')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказ продукт',
                'verbose_name_plural': 'Заказы продукты',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_product',
            field=models.ManyToManyField(through='home.OrderProduct', to='home.Product'),
        ),
    ]
